import {
  RiBankCardLine,
  RiBarChartBoxLine,
  RiCommandLine,
  RiEyeCloseLine,
  RiEyeLine,
  RiHome5Line,
  RiLockLine,
  RiLockUnlockLine,
  RiLogoutBoxRLine,
  RiMoonLine,
  RiPaintBrushLine,
  RiRefreshLine,
  RiSearchLine,
  RiSettings4Line,
  RiShoppingBag3Line,
  RiShoppingCart2Line,
  RiSunLine,
  RiUser3Line,
} from "@remixicon/react";

export const AppIcons = {
  billing: RiBankCardLine,
  command: RiCommandLine,
  editor: RiPaintBrushLine,
  eye: RiEyeLine,
  eyeOff: RiEyeCloseLine,
  home: RiHome5Line,
  insights: RiBarChartBoxLine,
  lock: RiLockLine,
  lockUnlock: RiLockUnlockLine,
  logout: RiLogoutBoxRLine,
  moon: RiMoonLine,
  orders: RiShoppingCart2Line,
  products: RiShoppingBag3Line,
  refresh: RiRefreshLine,
  search: RiSearchLine,
  settings: RiSettings4Line,
  sun: RiSunLine,
  user: RiUser3Line,
};

export type AppIcon = (typeof AppIcons)[keyof typeof AppIcons];
