import {
  RiArrowDownSLine,
  RiArrowLeftSLine,
  RiArrowRightSLine,
  RiArrowUpDownLine,
  RiArrowUpSLine,
  RiBankCardLine,
  RiBarChartBoxLine,
  RiCalendarLine,
  RiCheckLine,
  RiCloseLine,
  RiCommandLine,
  RiDeleteBin6Line,
  RiDownload2Line,
  RiErrorWarningLine,
  RiExternalLinkLine,
  RiEyeCloseLine,
  RiEyeLine,
  RiFileCopyLine,
  RiFilter3Line,
  RiFolderLine,
  RiFullscreenLine,
  RiHome5Line,
  RiImageLine,
  RiLayoutGridLine,
  RiListUnordered,
  RiLockLine,
  RiLockUnlockLine,
  RiLogoutBoxRLine,
  RiMoonLine,
  RiMore2Line,
  RiNodeTree,
  RiPaintBrushLine,
  RiPencilLine,
  RiPriceTag3Line,
  RiRefreshLine,
  RiSearchLine,
  RiSettings4Line,
  RiShoppingBag3Line,
  RiShoppingBagLine,
  RiShoppingCart2Line,
  RiStarFill,
  RiStarLine,
  RiSunLine,
  RiUploadCloud2Line,
  RiUser3Line,
} from "@remixicon/react";

export const AppIcons = {
  arrowDown: RiArrowDownSLine,
  arrowLeft: RiArrowLeftSLine,
  arrowRight: RiArrowRightSLine,
  arrowUp: RiArrowUpSLine,
  arrowUpDown: RiArrowUpDownLine,
  billing: RiBankCardLine,
  calendar: RiCalendarLine,
  check: RiCheckLine,
  close: RiCloseLine,
  command: RiCommandLine,
  copy: RiFileCopyLine,
  download: RiDownload2Line,
  editor: RiPaintBrushLine,
  error: RiErrorWarningLine,
  expand: RiFullscreenLine,
  externalLink: RiExternalLinkLine,
  filter: RiFilter3Line,
  folder: RiFolderLine,
  eye: RiEyeLine,
  eyeOff: RiEyeCloseLine,
  home: RiHome5Line,
  image: RiImageLine,
  grid: RiLayoutGridLine,
  list: RiListUnordered,
  edit: RiPencilLine,
  insights: RiBarChartBoxLine,
  lock: RiLockLine,
  lockUnlock: RiLockUnlockLine,
  logout: RiLogoutBoxRLine,
  moon: RiMoonLine,
  more: RiMore2Line,
  tree: RiNodeTree,
  orders: RiShoppingCart2Line,
  products: RiShoppingBag3Line,
  tag: RiPriceTag3Line,
  refresh: RiRefreshLine,
  search: RiSearchLine,
  settings: RiSettings4Line,
  shoppingBag: RiShoppingBagLine,
  star: RiStarLine,
  starFill: RiStarFill,
  sun: RiSunLine,
  trash: RiDeleteBin6Line,
  user: RiUser3Line,
  upload: RiUploadCloud2Line,
};

export type AppIcon = (typeof AppIcons)[keyof typeof AppIcons];
