import {
  RiArrowDownSLine,
  RiArrowLeftSLine,
  RiArrowUpDownLine,
  RiArrowUpSLine,
  RiBankCardLine,
  RiBarChartBoxLine,
  RiCheckLine,
  RiCommandLine,
  RiCloseLine,
  RiEyeCloseLine,
  RiEyeLine,
  RiErrorWarningLine,
  RiFileCopyLine,
  RiFilter3Line,
  RiHome5Line,
  RiImageLine,
  RiLockLine,
  RiLockUnlockLine,
  RiLogoutBoxRLine,
  RiMoonLine,
  RiMore2Line,
  RiPaintBrushLine,
  RiRefreshLine,
  RiSearchLine,
  RiSettings4Line,
  RiShoppingBagLine,
  RiShoppingBag3Line,
  RiShoppingCart2Line,
  RiSunLine,
  RiUser3Line,
} from "@remixicon/react";

export const AppIcons = {
  arrowDown: RiArrowDownSLine,
  arrowLeft: RiArrowLeftSLine,
  arrowUp: RiArrowUpSLine,
  arrowUpDown: RiArrowUpDownLine,
  billing: RiBankCardLine,
  check: RiCheckLine,
  close: RiCloseLine,
  command: RiCommandLine,
  copy: RiFileCopyLine,
  editor: RiPaintBrushLine,
  error: RiErrorWarningLine,
  filter: RiFilter3Line,
  eye: RiEyeLine,
  eyeOff: RiEyeCloseLine,
  home: RiHome5Line,
  image: RiImageLine,
  insights: RiBarChartBoxLine,
  lock: RiLockLine,
  lockUnlock: RiLockUnlockLine,
  logout: RiLogoutBoxRLine,
  moon: RiMoonLine,
  more: RiMore2Line,
  orders: RiShoppingCart2Line,
  products: RiShoppingBag3Line,
  refresh: RiRefreshLine,
  search: RiSearchLine,
  settings: RiSettings4Line,
  shoppingBag: RiShoppingBagLine,
  sun: RiSunLine,
  user: RiUser3Line,
};

export type AppIcon = (typeof AppIcons)[keyof typeof AppIcons];
