import { matrixProduct, singleAxisProduct } from "./catalog-builders.js";
import type { DemoShopDefinition } from "./types.js";

/** Afro shop — contemporary Ethiopian apparel and studio goods. */
export const afroShop: DemoShopDefinition = {
  ids: {
    tenant: "d3000000-0000-4000-8000-000000000001",
    domain: "d3000000-0000-4000-8000-000000000002",
    user: "d3000000-0000-4000-8000-000000000003",
    account: "d3000000-0000-4000-8000-000000000003:credential",
    membership: "d3000000-0000-4000-8000-000000000004",
    onboarding: "d3000000-0000-4000-8000-000000000005",
    storefrontRevision: "d3000000-0000-4000-8000-000000000006",
    storefrontConfig: "d3000000-0000-4000-8000-000000000007",
  },
  templateKey: "afro@1",
  tenant: {
    handle: "afrostudio",
    name: "AFRO Studio",
  },
  user: {
    email: "selam@afrostudio.ecs.et",
    name: "Selam Tesfaye",
    phone: "+251911100003",
  },
  paymentOnboarding: {
    status: "not_configured",
    notes: "Demo shop — connect Chapa in Settings when testing online pay.",
  },
  categories: [
    { name: "Jackets & Outerwear", handle: "demo-afro-jackets" },
    { name: "T-Shirts & Tops", handle: "demo-afro-tshirts" },
    { name: "Trousers & Denim", handle: "demo-afro-trousers" },
    { name: "Shirts", handle: "demo-afro-shirts" },
    { name: "Sets & Tracksuits", handle: "demo-afro-sets" },
    { name: "Accessories", handle: "demo-afro-accessories" },
    { name: "Knitwear & Sweaters", handle: "demo-afro-knitwear" },
    { name: "Footwear", handle: "demo-afro-footwear" },
  ],
  collections: [
    { title: "Women's Collection", handle: "demo-afro-women" },
    { title: "Men's Collection", handle: "demo-afro-men" },
    { title: "Kids' Collection", handle: "demo-afro-kids" },
    { title: "Accessories Collection", handle: "demo-afro-accessories-col" },
  ],
  customers: [
    {
      firstName: "Abebe",
      lastName: "Bikila",
      email: "abebe.bikila.afro@example.com",
      phone: "+251911400301",
      area: "Bole",
      address: "Bole Rwanda",
    },
    {
      firstName: "Tigist",
      lastName: "Assefa",
      email: "tigist.assefa.afro@example.com",
      phone: "+251911400302",
      area: "Sarbet",
      address: "Sarbet Pushkin Square",
    },
    {
      firstName: "Kenenisa",
      lastName: "Bekele",
      email: "kenenisa.bekele.afro@example.com",
      phone: "+251911400303",
      area: "Old Airport",
      address: "Old Airport Bisrate Gabriel",
    },
    {
      firstName: "Derartu",
      lastName: "Tulu",
      email: "derartu.tulu.afro@example.com",
      phone: "+251911400304",
      area: "Kazanchis",
      address: "Kazanchis UNECA",
    },
    {
      firstName: "Haile",
      lastName: "Gebrselassie",
      email: "haile.gebrselassie.afro@example.com",
      phone: "+251911400305",
      area: "CMC",
      address: "CMC Tsehay Real Estate",
    },
    {
      firstName: "Meseret",
      lastName: "Defar",
      email: "meseret.defar.afro@example.com",
      phone: "+251911400306",
      area: "Megenagna",
      address: "Megenagna Lem Hotel Area",
    },
    {
      firstName: "Sileshi",
      lastName: "Sihine",
      email: "sileshi.sihine.afro@example.com",
      phone: "+251911400307",
      area: "Piassa",
      address: "Piassa Arada Posta",
    },
    {
      firstName: "Genzebe",
      lastName: "Dibaba",
      email: "genzebe.dibaba.afro@example.com",
      phone: "+251911400308",
      area: "Gotera",
      address: "Gotera Condominium",
    },
  ],
  products: [
    {
      ...singleAxisProduct(
        "Suede Zip Jacket",
        "demo-afro-suede-zip-jacket",
        "outerwear",
        10240,
        "Size",
        ["S", "M", "L", "XL", "XXL"],
        [15, 12, 8, 4, 2],
        "Precision-crafted from premium supple goat suede with a clean minimal collar, satin interior lining, and custom brushed gunmetal hardware. Designed for a sharp silhouette that transitions effortlessly across every season.",
      ),
      categoryHandle: "demo-afro-jackets",
      collectionHandle: "demo-afro-men",
    },
    {
      ...singleAxisProduct(
        "Relaxed Wool Trousers",
        "demo-afro-relaxed-wool-trousers",
        "bottoms",
        7850,
        "Size",
        ["S", "M", "L", "XL"],
        [12, 10, 5, 2],
        "Tailored with comfortable ease, these relaxed wool trousers feature front pleats, slanted pockets, and a refined drape suitable for formal and casual settings alike.",
      ),
      categoryHandle: "demo-afro-trousers",
      collectionHandle: "demo-afro-men",
    },
    {
      ...singleAxisProduct(
        "Straight-Leg Denim Jeans",
        "demo-afro-straight-leg-denim-jeans",
        "bottoms",
        4950,
        "Size",
        ["S", "M", "L", "XL"],
        [14, 10, 8, 4],
        "Classic straight-leg cut crafted from heavyweight selvedge denim. Finished with authentic copper hardware and vintage wash detailing.",
      ),
      categoryHandle: "demo-afro-trousers",
      collectionHandle: "demo-afro-men",
    },
    {
      ...singleAxisProduct(
        "Oxford Cotton Shirt",
        "demo-afro-oxford-cotton-shirt",
        "shirts",
        5430,
        "Size",
        ["S", "M", "L", "XL"],
        [16, 12, 8, 3],
        "Woven from pure long-staple organic cotton, this timeless Oxford shirt features mother-of-pearl buttons and a comfortable regular fit.",
      ),
      categoryHandle: "demo-afro-shirts",
      collectionHandle: "demo-afro-women",
    },
    {
      ...singleAxisProduct(
        "Utilitarian Overshirt",
        "demo-afro-utilitarian-overshirt",
        "outerwear",
        5990,
        "Size",
        ["S", "M", "L", "XL"],
        [14, 9, 6, 2],
        "A versatile layering piece designed with functional patch pockets, point collar, and concealed snap closures in durable twill cotton.",
      ),
      categoryHandle: "demo-afro-jackets",
      collectionHandle: "demo-afro-men",
    },
    {
      ...singleAxisProduct(
        "Camp-Collar Linen Shirt",
        "demo-afro-camp-collar-linen-shirt",
        "shirts",
        4200,
        "Size",
        ["S", "M", "L", "XL"],
        [10, 8, 5, 2],
        "Breezy, lightweight camp-collar shirt cut from breathable French linen. Perfect for warmer climates and easygoing summer styling.",
      ),
      categoryHandle: "demo-afro-shirts",
      collectionHandle: "demo-afro-women",
    },
    {
      ...singleAxisProduct(
        "Down Quilted Puffer",
        "demo-afro-down-quilted-puffer",
        "outerwear",
        14800,
        "Size",
        ["S", "M", "L", "XL"],
        [8, 6, 4, 1],
        "High-loft down insulation encased in water-repellent ripstop shell. Delivers superior warmth and wind resistance in cold conditions.",
      ),
      categoryHandle: "demo-afro-jackets",
      collectionHandle: "demo-afro-women",
    },
    {
      ...singleAxisProduct(
        "Club Graphic T-Shirt",
        "demo-afro-club-graphic-t-shirt",
        "tops",
        2650,
        "Size",
        ["S", "M", "L", "XL"],
        [20, 15, 10, 5],
        "Everyday classic crewneck crafted from soft mid-weight cotton jersey featuring minimalist embroidered heritage branding.",
      ),
      categoryHandle: "demo-afro-tshirts",
      collectionHandle: "demo-afro-kids",
    },
    {
      ...singleAxisProduct(
        "SST 3-Stripes Tracksuit",
        "demo-afro-sst-tracksuit",
        "sets",
        8900,
        "Size",
        ["S", "M", "L", "XL"],
        [12, 10, 6, 3],
        "Iconic track jacket and pants set made with recycled tricot fabric, ribbed details, and signature 3-stripes down the sleeves and legs.",
      ),
      categoryHandle: "demo-afro-sets",
      collectionHandle: "demo-afro-men",
    },
    {
      ...singleAxisProduct(
        "Sherpa Corduroy Jacket",
        "demo-afro-sherpa-corduroy-jacket",
        "outerwear",
        11500,
        "Size",
        ["S", "M", "L", "XL"],
        [9, 7, 4, 2],
        "Chunky ridge corduroy exterior lined with plush sherpa fleece. Features dual chest flap pockets and reinforced stitching.",
      ),
      categoryHandle: "demo-afro-jackets",
      collectionHandle: "demo-afro-men",
    },
    {
      ...singleAxisProduct(
        "Tailored Pleat Trousers",
        "demo-afro-tailored-pleat-trousers",
        "bottoms",
        7120,
        "Size",
        ["S", "M", "L", "XL"],
        [11, 8, 5, 2],
        "Sophisticated tailored trousers with double pleats and an adjustable waist tab for an immaculate bespoke silhouette.",
      ),
      categoryHandle: "demo-afro-trousers",
      collectionHandle: "demo-afro-women",
    },
    {
      ...singleAxisProduct(
        "Leather Crossbody Pouch",
        "demo-afro-leather-crossbody-pouch",
        "accessories",
        6200,
        "Color",
        ["Dark Brown", "Black"],
        [12, 8],
        "Supple nappa leather crossbody bag with minimalist hardware and knotted shoulder strap.",
      ),
      categoryHandle: "demo-afro-accessories",
      collectionHandle: "demo-afro-accessories-col",
    },
    {
      ...singleAxisProduct(
        "Cotton Minimalist Beanie",
        "demo-afro-cotton-minimalist-beanie",
        "accessories",
        1850,
        "Color",
        ["Black", "Olive"],
        [25, 20],
        "Ribbed organic cotton watch cap beanie with subtle tonal brand woven label.",
      ),
      categoryHandle: "demo-afro-accessories",
      collectionHandle: "demo-afro-accessories-col",
    },
    {
      ...singleAxisProduct(
        "Essential Everyday Tote",
        "demo-afro-essential-everyday-tote",
        "accessories",
        4500,
        "Color",
        ["Black", "Tan"],
        [18, 14],
        "Durable nylon canvas tote bag with reinforced dual carry handles and internal organizer sleeve.",
      ),
      categoryHandle: "demo-afro-accessories",
      collectionHandle: "demo-afro-accessories-col",
    },
    {
      ...matrixProduct(
        "Heavyweight Boxy Tee",
        "demo-afro-heavyweight-boxy-tee",
        "tops",
        3450,
        [
          { title: "Size", values: ["S", "M", "L", "XL"] },
          { title: "Color", values: ["Off-White", "Black"] },
        ],
        [15, 12, 8, 4, 12, 10, 6, 2],
        "Constructed with a hefty 280gsm organic combed cotton in a relaxed boxy cut with drop shoulders.",
      ),
      categoryHandle: "demo-afro-tshirts",
      collectionHandle: "demo-afro-kids",
    },
    {
      ...singleAxisProduct(
        "Structured Knit Cardigan",
        "demo-afro-structured-knit-cardigan",
        "knitwear",
        9950,
        "Size",
        ["S", "M", "L", "XL"],
        [10, 7, 4, 1],
        "Chunky ribbed merino wool cardigan with horn buttons and dropped shoulder silhouette.",
      ),
      categoryHandle: "demo-afro-knitwear",
      collectionHandle: "demo-afro-women",
    },
  ],
};
