import { matrixProduct, singleAxisProduct } from "./catalog-builders.js";
import type { DemoShopDefinition } from "./types.js";

/** Afro shop — contemporary Ethiopian apparel and studio goods. */
export const afroShop: DemoShopDefinition = {
  ids: {
    tenant: "d3000000-0000-4000-8000-000000000001",
    domain: "d3000000-0000-4000-8000-000000000002",
    user: "d3000000-0000-4000-8000-000000000003",
    account: "d3000000-0000-4000-8000-000000000003:credential",
    membership: "d3000000-0000-4000-8000-000000000004",
    onboarding: "d3000000-0000-4000-8000-000000000005",
    storefrontRevision: "d3000000-0000-4000-8000-000000000006",
    storefrontConfig: "d3000000-0000-4000-8000-000000000007",
  },
  templateKey: "afro@1",
  tenant: {
    handle: "afrostudio",
    name: "AFRO Studio",
  },
  user: {
    email: "selam@afrostudio.ecs.et",
    name: "Selam Tesfaye",
    phone: "+251911100003",
  },
  paymentOnboarding: {
    status: "not_configured",
    notes: "Demo shop — connect Chapa in Settings when testing online pay.",
  },
  categories: [
    { name: "Jackets & Outerwear", handle: "demo-afro-jackets" },
    { name: "T-Shirts & Tops", handle: "demo-afro-tshirts" },
    { name: "Trousers & Denim", handle: "demo-afro-trousers" },
    { name: "Shirts", handle: "demo-afro-shirts" },
    { name: "Accessories", handle: "demo-afro-accessories" },
    { name: "Knitwear & Sweaters", handle: "demo-afro-knitwear" },
    { name: "Footwear", handle: "demo-afro-footwear" },
  ],
  collections: [
    { title: "Women's Collection", handle: "demo-afro-women" },
    { title: "Men's Collection", handle: "demo-afro-men" },
    { title: "Accessories Collection", handle: "demo-afro-accessories-col" },
  ],
  customers: [
    {
      firstName: "Abebe",
      lastName: "Bikila",
      email: "abebe.bikila.afro@example.com",
      phone: "+251911400301",
      area: "Bole",
      address: "Bole Rwanda",
    },
    {
      firstName: "Tigist",
      lastName: "Assefa",
      email: "tigist.assefa.afro@example.com",
      phone: "+251911400302",
      area: "Sarbet",
      address: "Sarbet Pushkin Square",
    },
    {
      firstName: "Kenenisa",
      lastName: "Bekele",
      email: "kenenisa.bekele.afro@example.com",
      phone: "+251911400303",
      area: "Old Airport",
      address: "Old Airport Bisrate Gabriel",
    },
    {
      firstName: "Derartu",
      lastName: "Tulu",
      email: "derartu.tulu.afro@example.com",
      phone: "+251911400304",
      area: "Kazanchis",
      address: "Kazanchis UNECA",
    },
    {
      firstName: "Haile",
      lastName: "Gebrselassie",
      email: "haile.gebrselassie.afro@example.com",
      phone: "+251911400305",
      area: "CMC",
      address: "CMC Tsehay Real Estate",
    },
    {
      firstName: "Meseret",
      lastName: "Defar",
      email: "meseret.defar.afro@example.com",
      phone: "+251911400306",
      area: "Megenagna",
      address: "Megenagna Lem Hotel Area",
    },
    {
      firstName: "Sileshi",
      lastName: "Sihine",
      email: "sileshi.sihine.afro@example.com",
      phone: "+251911400307",
      area: "Piassa",
      address: "Piassa Arada Posta",
    },
    {
      firstName: "Genzebe",
      lastName: "Dibaba",
      email: "genzebe.dibaba.afro@example.com",
      phone: "+251911400308",
      area: "Gotera",
      address: "Gotera Condominium",
    },
  ],
  products: [
    {
      ...singleAxisProduct(
        "Suede Zip Jacket",
        "demo-afro-suede-zip-jacket",
        "outerwear",
        10240,
        "Size",
        ["S", "M", "L", "XL"],
        [15, 8, 4, 2],
        "Premium suede zip jacket with tailored silhouette, minimalist collar, and metal hardware.",
      ),
      categoryHandle: "demo-afro-jackets",
      collectionHandle: "demo-afro-men",
    },
    {
      ...singleAxisProduct(
        "Relaxed Wool Trousers",
        "demo-afro-relaxed-wool-trousers",
        "bottoms",
        7850,
        "Size",
        ["30", "32", "34", "36"],
        [12, 10, 5, 0],
        "Relaxed fit trousers crafted from fine wool blend with clean front pleats.",
      ),
      categoryHandle: "demo-afro-trousers",
      collectionHandle: "demo-afro-men",
    },
    {
      ...matrixProduct(
        "Heavyweight Box Tee",
        "demo-afro-heavyweight-box-tee",
        "tops",
        3400,
        [
          { title: "Size", values: ["S", "M", "L", "XL"] },
          { title: "Color", values: ["Off-White", "Washed Black"] },
        ],
        [20, 15, 8, 3, 18, 12, 6, 2],
        "Heavyweight 280gsm organic cotton boxy fit tee with ribbed neck.",
      ),
      categoryHandle: "demo-afro-tshirts",
      collectionHandle: "demo-afro-women",
    },
    {
      ...singleAxisProduct(
        "Structured Overshirt",
        "demo-afro-structured-overshirt",
        "outerwear",
        6200,
        "Size",
        ["M", "L", "XL"],
        [14, 7, 3],
        "Durable twill overshirt with chest patch pockets and horn buttons.",
      ),
      categoryHandle: "demo-afro-jackets",
      collectionHandle: "demo-afro-men",
    },
    {
      ...matrixProduct(
        "Tailored Linen Shirt",
        "demo-afro-tailored-linen-shirt",
        "shirts",
        5600,
        [
          { title: "Size", values: ["S", "M", "L"] },
          { title: "Color", values: ["Sand", "Olive"] },
        ],
        [10, 6, 2, 8, 4, 1],
        "Breathable pure linen shirt with relaxed spread collar.",
      ),
      categoryHandle: "demo-afro-shirts",
      collectionHandle: "demo-afro-women",
    },
    {
      ...singleAxisProduct(
        "Leather Crossbody Bag",
        "demo-afro-leather-crossbody-bag",
        "accessories",
        8900,
        "Color",
        ["Espresso", "Cognac"],
        [8, 5],
        "Full-grain Ethiopian leather crossbody bag with adjustable strap and brass zip.",
      ),
      categoryHandle: "demo-afro-accessories",
      collectionHandle: "demo-afro-accessories-col",
    },
    {
      ...singleAxisProduct(
        "Wool Blend Cardigan",
        "demo-afro-wool-blend-cardigan",
        "knitwear",
        9100,
        "Size",
        ["S", "M", "L"],
        [11, 6, 2],
        "Cozy textured knit cardigan with dropped shoulders and ribbed cuffs.",
      ),
      categoryHandle: "demo-afro-knitwear",
      collectionHandle: "demo-afro-women",
    },
    {
      ...singleAxisProduct(
        "Pleated Wide Trousers",
        "demo-afro-pleated-wide-trousers",
        "bottoms",
        8200,
        "Size",
        ["28", "30", "32"],
        [9, 5, 2],
        "High-waisted wide leg trousers with double front pleats and fluid drape.",
      ),
      categoryHandle: "demo-afro-trousers",
      collectionHandle: "demo-afro-women",
    },
    {
      ...singleAxisProduct(
        "Minimalist Leather Belt",
        "demo-afro-minimalist-leather-belt",
        "accessories",
        2400,
        "Size",
        ["85cm", "95cm", "105cm"],
        [25, 18, 10],
        "Handcrafted vegetable-tanned leather belt with matte brushed buckle.",
      ),
      categoryHandle: "demo-afro-accessories",
      collectionHandle: "demo-afro-accessories-col",
    },
    {
      ...matrixProduct(
        "Everyday Cotton Crewneck",
        "demo-afro-everyday-cotton-crewneck",
        "tops",
        4500,
        [
          { title: "Size", values: ["S", "M", "L", "XL"] },
          { title: "Color", values: ["Heather Grey", "Charcoal"] },
        ],
        [16, 12, 8, 2, 14, 10, 5, 1],
        "French terry crewneck sweatshirt with classic raglan sleeve stitching.",
      ),
      categoryHandle: "demo-afro-tshirts",
      collectionHandle: "demo-afro-men",
    },
    {
      ...singleAxisProduct(
        "Chelsea Leather Boots",
        "demo-afro-chelsea-leather-boots",
        "footwear",
        11500,
        "EU Size",
        ["40", "41", "42", "43", "44"],
        [5, 8, 10, 6, 2],
        "Classic Chelsea boots in supple calfskin with elastic side gussets.",
      ),
      categoryHandle: "demo-afro-footwear",
      collectionHandle: "demo-afro-men",
    },
    {
      ...singleAxisProduct(
        "Merino Wool Scarf",
        "demo-afro-merino-wool-scarf",
        "accessories",
        3200,
        "Color",
        ["Oatmeal", "Charcoal"],
        [20, 15],
        "Ultra-soft pure merino wool scarf with clean fringed edges.",
      ),
      categoryHandle: "demo-afro-accessories",
      collectionHandle: "demo-afro-accessories-col",
    },
  ],
};
