import { matrixProduct, singleAxisProduct } from "./catalog-builders.js";
import type { DemoShopDefinition } from "./types.js";

export const fashionShop: DemoShopDefinition = {
  ids: {
    tenant: "d2000000-0000-4000-8000-000000000001",
    domain: "d2000000-0000-4000-8000-000000000002",
    user: "d2000000-0000-4000-8000-000000000003",
    account: "d2000000-0000-4000-8000-000000000003:credential",
    membership: "d2000000-0000-4000-8000-000000000004",
    onboarding: "d2000000-0000-4000-8000-000000000005",
    storefrontRevision: "d2000000-0000-4000-8000-000000000006",
    storefrontConfig: "d2000000-0000-4000-8000-000000000007",
  },
  templateKey: "luvia@1",
  tenant: {
    handle: "bolestyle",
    name: "Luvia Botanicals",
  },
  user: {
    email: "liya@bolestyle.ecs.et",
    name: "Liya Tadesse",
    phone: "+251911100002",
  },
  paymentOnboarding: {
    status: "not_configured",
    notes: "Demo shop — connect Chapa in Settings when testing online pay.",
  },
  categories: [
    { name: "Skincare", handle: "demo-fashion-skincare" },
    {
      name: "Serums & Elixirs",
      handle: "demo-fashion-skincare-serums",
      parentHandle: "demo-fashion-skincare",
    },
    {
      name: "Cleansers & Toners",
      handle: "demo-fashion-skincare-cleansers",
      parentHandle: "demo-fashion-skincare",
    },
    {
      name: "Moisturizers & Creams",
      handle: "demo-fashion-skincare-creams",
      parentHandle: "demo-fashion-skincare",
    },
    { name: "Makeup & Complexion", handle: "demo-fashion-makeup" },
    {
      name: "Lipsticks & Tints",
      handle: "demo-fashion-makeup-lips",
      parentHandle: "demo-fashion-makeup",
    },
    { name: "Fragrance & Scents", handle: "demo-fashion-fragrance" },
    { name: "Body & Bath", handle: "demo-fashion-body" },
  ],
  collections: [
    { title: "Best Sellers", handle: "demo-fashion-new-season" },
    { title: "Daily Rituals", handle: "demo-fashion-essentials" },
    { title: "Gift Sets & Curations", handle: "demo-fashion-gift-picks" },
  ],
  customers: [
    {
      firstName: "Mahi",
      lastName: "Kebede",
      email: "mahi.kebede.style@example.com",
      phone: "+251911300201",
      area: "Bole",
      address: "Bole Atlas",
    },
    {
      firstName: "Yonas",
      lastName: "Assefa",
      email: "yonas.assefa.style@example.com",
      phone: "+251911300202",
      area: "Sarbet",
      address: "Sarbet Gabriel",
    },
    {
      firstName: "Ruth",
      lastName: "Getachew",
      email: "ruth.getachew.style@example.com",
      phone: "+251911300203",
      area: "Old Airport",
      address: "Old Airport Residence",
    },
    {
      firstName: "Samuel",
      lastName: "Berhanu",
      email: "samuel.berhanu.style@example.com",
      phone: "+251911300204",
      area: "Megenagna",
      address: "Megenagna Square",
    },
    {
      firstName: "Selam",
      lastName: "Abebe",
      email: "selam.abebe.style@example.com",
      phone: "+251911300205",
      area: "Kazanchis",
      address: "Kazanchis Twin Towers",
    },
    {
      firstName: "Nahom",
      lastName: "Fikru",
      email: "nahom.fikru.style@example.com",
      phone: "+251911300206",
      area: "CMC",
      address: "CMC Summit",
    },
    {
      firstName: "Helen",
      lastName: "Worku",
      email: "helen.worku.style@example.com",
      phone: "+251911300207",
      area: "Piassa",
      address: "Piassa Churchill",
    },
    {
      firstName: "Meron",
      lastName: "Desta",
      email: "meron.desta.style@example.com",
      phone: "+251911300208",
      area: "Hayahulet",
      address: "Hayahulet Mazoria",
    },
    {
      firstName: "Eyob",
      lastName: "Solomon",
      email: "eyob.solomon.style@example.com",
      phone: "+251911300209",
      area: "Lebu",
      address: "Lebu Mebrat Hail",
    },
  ],
  products: [
    {
      ...singleAxisProduct(
        "Hydra-Luminous Niacinamide Serum",
        "demo-fashion-hydra-serum",
        "skincare",
        3400,
        "Volume",
        ["30ml", "50ml"],
        [24, 16],
        "Formulated with 10% pure Niacinamide and multi-molecular hyaluronic acid to restore skin barrier health, even tone, and deliver an instant glass-skin radiance. Lightweight, fast-absorbing, and fragrance-free.",
      ),
      categoryHandle: "demo-fashion-skincare-serums",
      collectionHandle: "demo-fashion-new-season",
    },
    {
      ...singleAxisProduct(
        "Botanical Radiance Face Oil",
        "demo-fashion-botanical-face-oil",
        "skincare",
        3850,
        "Volume",
        ["30ml", "50ml"],
        [18, 12],
        "A cold-pressed golden elixir blending rosehip, marula, and squalane oils. Infuses deep cellular hydration, locks in moisture, and leaves a silky, non-greasy cashmere finish.",
      ),
      categoryHandle: "demo-fashion-skincare-serums",
      collectionHandle: "demo-fashion-essentials",
    },
    {
      ...singleAxisProduct(
        "Restorative Peptide Night Cream",
        "demo-fashion-peptide-night-cream",
        "skincare",
        4200,
        "Size",
        ["50ml"],
        [22, 14],
        "An intensive overnight rejuvenation cream enriched with copper tripeptides, ceramides, and fermented yeast extract. Promotes natural collagen synthesis and visibly firms skin by morning.",
      ),
      categoryHandle: "demo-fashion-skincare-creams",
      collectionHandle: "demo-fashion-new-season",
    },
    {
      ...singleAxisProduct(
        "Gentle Clarifying Cleansing Gel",
        "demo-fashion-clarifying-cleanser",
        "skincare",
        1950,
        "Volume",
        ["150ml", "200ml"],
        [30, 18],
        "Sulfate-free pH-balanced foaming gel infused with green tea extract and amino acids. Gently dissolves waterproof makeup, pollutants, and excess sebum without stripping the skin's natural moisture.",
      ),
      categoryHandle: "demo-fashion-skincare-cleansers",
      collectionHandle: "demo-fashion-essentials",
    },
    {
      ...singleAxisProduct(
        "Rosewater Balancing Facial Mist",
        "demo-fashion-facial-mist",
        "skincare",
        1650,
        "Volume",
        ["100ml", "150ml"],
        [35, 20],
        "Steam-distilled organic damask rosewater with witch hazel and aloe vera. Restores skin pH after cleansing and provides refreshing hydration throughout the day.",
      ),
      categoryHandle: "demo-fashion-skincare-cleansers",
      collectionHandle: "demo-fashion-essentials",
    },
    {
      ...singleAxisProduct(
        "Purifying Mineral Clay Mask",
        "demo-fashion-mineral-clay-mask",
        "skincare",
        2600,
        "Size",
        ["75ml", "100ml"],
        [20, 15],
        "French kaolin and bentonite clay infused with botanical charcoal and willow bark. Detoxifies pores, refines skin texture, and reveals a smooth, balanced complexion.",
      ),
      categoryHandle: "demo-fashion-skincare-creams",
      collectionHandle: "demo-fashion-essentials",
    },
    {
      ...singleAxisProduct(
        "Vitamin C Brightening Eye Elixir",
        "demo-fashion-brightening-eye-elixir",
        "skincare",
        2900,
        "Volume",
        ["15ml"],
        [28, 14],
        "Concentrated stabilized Vitamin C and caffeine serum targeting dark circles, under-eye puffiness, and fine lines. Features a cooling applicator for instantaneous depuffing.",
      ),
      categoryHandle: "demo-fashion-skincare-serums",
      collectionHandle: "demo-fashion-new-season",
    },
    {
      ...singleAxisProduct(
        "Nourishing Ceramide Barrier Balm",
        "demo-fashion-barrier-balm",
        "skincare",
        2350,
        "Size",
        ["40ml", "75ml"],
        [25, 15],
        "A multi-use soothing balm packed with 5 essential ceramides, centella asiatica, and shea butter. Instantly relieves irritated, dry, or sensitized skin barriers.",
      ),
      categoryHandle: "demo-fashion-skincare-creams",
      collectionHandle: "demo-fashion-essentials",
    },
    {
      ...singleAxisProduct(
        "Velvet Matte Lip Color",
        "demo-fashion-velvet-matte-lipstick",
        "makeup",
        1750,
        "Shade",
        ["Dusty Rose", "Crimson Velvet", "Nude Bloom"],
        [25, 20, 30],
        "Weightless high-pigment matte lipstick infused with jojoba oil and vitamin E for comfortable, non-drying all-day wear with a soft-focus velvet finish.",
      ),
      categoryHandle: "demo-fashion-makeup-lips",
      collectionHandle: "demo-fashion-new-season",
    },
    {
      ...singleAxisProduct(
        "Silk Glow Liquid Highlighter",
        "demo-fashion-liquid-highlighter",
        "makeup",
        2200,
        "Shade",
        ["Champagne Sun", "Rose Gold", "Soft Bronze"],
        [18, 14, 12],
        "Ultra-fine light-reflecting liquid illuminator that seamlessly melts into skin. Can be worn alone on high points of the face or mixed with foundation for an all-over dewy glow.",
      ),
      categoryHandle: "demo-fashion-makeup",
      collectionHandle: "demo-fashion-new-season",
    },
    {
      ...singleAxisProduct(
        "Santal & Cedar Eau de Parfum",
        "demo-fashion-eau-de-parfum",
        "fragrance",
        6800,
        "Volume",
        ["50ml", "100ml"],
        [12, 6],
        "An intimate, evocative fragrance combining creamy Australian sandalwood, smoked Virginia cedarwood, spicy cardamom, and a warm amber musky base.",
      ),
      categoryHandle: "demo-fashion-fragrance",
      collectionHandle: "demo-fashion-gift-picks",
    },
    {
      ...singleAxisProduct(
        "Velvet Amber Body Lotion",
        "demo-fashion-body-lotion",
        "body",
        2100,
        "Volume",
        ["250ml", "400ml"],
        [22, 14],
        "A silk-textured hydrating body lotion with notes of warm amber, vanilla orchid, and sweet almond oil. Absorbs instantly for velvety touchable softness.",
      ),
      categoryHandle: "demo-fashion-body",
      collectionHandle: "demo-fashion-essentials",
    },
    {
      ...singleAxisProduct(
        "Hydrating Botanical Body Butter",
        "demo-fashion-botanical-body-butter",
        "body",
        2750,
        "Size",
        ["180ml"],
        [19, 11],
        "Whipped organic shea butter and cocoa butter infused with vitamin E and botanical oils. Deeply nourishes dry skin, leaving a lasting luminous sheen.",
      ),
      categoryHandle: "demo-fashion-body",
      collectionHandle: "demo-fashion-essentials",
    },
    {
      ...singleAxisProduct(
        "The Signature Ritual Discovery Gift Box",
        "demo-fashion-signature-gift-set",
        "sets",
        5500,
        "Tier",
        ["Core Ritual Trio", "Grand Luxury Edition"],
        [15, 8],
        "A curated deluxe box featuring our best-selling botanical serum, peptide cream, and cleansing gel in a handcrafted presentation case. The quintessential gift of self-care.",
      ),
      categoryHandle: "demo-fashion-skincare",
      collectionHandle: "demo-fashion-gift-picks",
    },
  ],
};
