import { matrixProduct, singleAxisProduct } from "./catalog-builders.js";
import type { DemoShopDefinition } from "./types.js";

export const fashionShop: DemoShopDefinition = {
  ids: {
    tenant: "d2000000-0000-4000-8000-000000000001",
    domain: "d2000000-0000-4000-8000-000000000002",
    user: "d2000000-0000-4000-8000-000000000003",
    account: "d2000000-0000-4000-8000-000000000003:credential",
    membership: "d2000000-0000-4000-8000-000000000004",
    onboarding: "d2000000-0000-4000-8000-000000000005",
    storefrontRevision: "d2000000-0000-4000-8000-000000000006",
    storefrontConfig: "d2000000-0000-4000-8000-000000000007",
  },
  templateKey: "luvia@1",
  tenant: {
    handle: "bolestyle",
    name: "Bole Style",
  },
  user: {
    email: "liya@bolestyle.ecs.et",
    name: "Liya Tadesse",
    phone: "+251911100002",
  },
  paymentOnboarding: {
    status: "not_configured",
    notes: "Demo shop — connect Chapa in Settings when testing online pay.",
  },
  categories: [
    { name: "Women", handle: "demo-fashion-women" },
    { name: "Dresses", handle: "demo-fashion-women-dresses", parentHandle: "demo-fashion-women" },
    { name: "Tops", handle: "demo-fashion-women-tops", parentHandle: "demo-fashion-women" },
    { name: "Men", handle: "demo-fashion-men" },
    { name: "Bottoms", handle: "demo-fashion-men-bottoms", parentHandle: "demo-fashion-men" },
    { name: "Outerwear", handle: "demo-fashion-men-outerwear", parentHandle: "demo-fashion-men" },
    { name: "Footwear", handle: "demo-fashion-footwear" },
    { name: "Accessories", handle: "demo-fashion-accessories" },
  ],
  collections: [
    { title: "New Season", handle: "demo-fashion-new-season" },
    { title: "Everyday Essentials", handle: "demo-fashion-essentials" },
    { title: "Gift Picks", handle: "demo-fashion-gift-picks" },
  ],
  customers: [
    {
      firstName: "Mahi",
      lastName: "Kebede",
      email: "mahi.kebede.style@example.com",
      phone: "+251911300201",
      area: "Bole",
      address: "Bole Atlas",
    },
    {
      firstName: "Yonas",
      lastName: "Assefa",
      email: "yonas.assefa.style@example.com",
      phone: "+251911300202",
      area: "Sarbet",
      address: "Sarbet Gabriel",
    },
    {
      firstName: "Ruth",
      lastName: "Getachew",
      email: "ruth.getachew.style@example.com",
      phone: "+251911300203",
      area: "Old Airport",
      address: "Old Airport Residence",
    },
    {
      firstName: "Samuel",
      lastName: "Berhanu",
      email: "samuel.berhanu.style@example.com",
      phone: "+251911300204",
      area: "Megenagna",
      address: "Megenagna Square",
    },
    {
      firstName: "Selam",
      lastName: "Abebe",
      email: "selam.abebe.style@example.com",
      phone: "+251911300205",
      area: "Kazanchis",
      address: "Kazanchis Twin Towers",
    },
    {
      firstName: "Nahom",
      lastName: "Fikru",
      email: "nahom.fikru.style@example.com",
      phone: "+251911300206",
      area: "CMC",
      address: "CMC Summit",
    },
    {
      firstName: "Helen",
      lastName: "Worku",
      email: "helen.worku.style@example.com",
      phone: "+251911300207",
      area: "Piassa",
      address: "Piassa Churchill",
    },
    {
      firstName: "Meron",
      lastName: "Desta",
      email: "meron.desta.style@example.com",
      phone: "+251911300208",
      area: "Hayahulet",
      address: "Hayahulet Mazoria",
    },
    {
      firstName: "Eyob",
      lastName: "Solomon",
      email: "eyob.solomon.style@example.com",
      phone: "+251911300209",
      area: "Lebu",
      address: "Lebu Mebrat Hail",
    },
  ],
  products: [
    {
      ...matrixProduct(
        "Linen Midi Dress",
        "demo-fashion-linen-midi",
        "women",
        3200,
        [
          { title: "Size", values: ["S", "M", "L"] },
          { title: "Color", values: ["Ivory", "Sage"] },
        ],
        [20, 12, 8, 3, 0, 15],
      ),
      categoryHandle: "demo-fashion-women-dresses",
      collectionHandle: "demo-fashion-new-season",
    },
    {
      ...matrixProduct(
        "Cotton Wrap Blouse",
        "demo-fashion-wrap-blouse",
        "women",
        1850,
        [
          { title: "Size", values: ["S", "M", "L"] },
          { title: "Color", values: ["White", "Blush"] },
        ],
        [18, 10, 5, 2, 0, 9],
      ),
      categoryHandle: "demo-fashion-women-tops",
      collectionHandle: "demo-fashion-essentials",
    },
    {
      ...singleAxisProduct(
        "Relaxed Chino Trousers",
        "demo-fashion-chino",
        "men",
        2100,
        "Waist",
        ["30", "32", "34"],
        [14, 8, 3],
      ),
      categoryHandle: "demo-fashion-men-bottoms",
      collectionHandle: "demo-fashion-essentials",
    },
    {
      ...matrixProduct(
        "Essential Crew Tee",
        "demo-fashion-crew-tee",
        "men",
        890,
        [
          { title: "Size", values: ["S", "M", "L", "XL"] },
          { title: "Color", values: ["Black", "White", "Olive"] },
        ],
        [30, 25, 18, 10, 4, 0, 22, 15, 8, 6, 2, 12],
      ),
      categoryHandle: "demo-fashion-men",
      collectionHandle: "demo-fashion-essentials",
    },
    {
      ...singleAxisProduct(
        "Leather Crossbody Bag",
        "demo-fashion-crossbody",
        "accessories",
        4500,
        "Color",
        ["Cognac", "Black"],
        [7, 2],
      ),
      categoryHandle: "demo-fashion-accessories",
      collectionHandle: "demo-fashion-gift-picks",
    },
    {
      ...singleAxisProduct(
        "Canvas Tote",
        "demo-fashion-canvas-tote",
        "accessories",
        780,
        "Color",
        ["Natural", "Olive"],
        [40, 18],
      ),
      categoryHandle: "demo-fashion-accessories",
      collectionHandle: "demo-fashion-essentials",
    },
    {
      ...singleAxisProduct(
        "Everyday Sneakers",
        "demo-fashion-sneakers",
        "footwear",
        3600,
        "EU Size",
        ["40", "42", "44"],
        [10, 4, 0],
      ),
      categoryHandle: "demo-fashion-footwear",
      collectionHandle: "demo-fashion-new-season",
    },
    {
      ...singleAxisProduct(
        "Ankle Boots",
        "demo-fashion-ankle-boots",
        "footwear",
        5200,
        "EU Size",
        ["38", "40", "42"],
        [6, 3, 1],
      ),
      categoryHandle: "demo-fashion-footwear",
      collectionHandle: "demo-fashion-gift-picks",
    },
    {
      ...singleAxisProduct(
        "Silk Scarf Print",
        "demo-fashion-silk-scarf",
        "accessories",
        1200,
        "Color",
        ["Ivory", "Indigo"],
        [22, 9],
      ),
      categoryHandle: "demo-fashion-accessories",
      collectionHandle: "demo-fashion-gift-picks",
    },
    {
      ...matrixProduct(
        "Structured Blazer",
        "demo-fashion-blazer",
        "women",
        4800,
        [
          { title: "Size", values: ["S", "M", "L"] },
          { title: "Color", values: ["Navy", "Camel"] },
        ],
        [8, 5, 2, 0, 4, 1],
      ),
      categoryHandle: "demo-fashion-women-tops",
      collectionHandle: "demo-fashion-new-season",
    },
    {
      ...singleAxisProduct(
        "Denim Jacket",
        "demo-fashion-denim-jacket",
        "men",
        3900,
        "Size",
        ["M", "L", "XL"],
        [11, 6, 2],
      ),
      categoryHandle: "demo-fashion-men-outerwear",
      collectionHandle: "demo-fashion-new-season",
    },
    {
      ...singleAxisProduct(
        "Gift Card Bundle Box",
        "demo-fashion-gift-box",
        "accessories",
        2500,
        "Tier",
        ["Classic", "Premium"],
        [50, 20],
      ),
      categoryHandle: "demo-fashion-accessories",
      collectionHandle: "demo-fashion-gift-picks",
    },
  ],
};
