import { matrixProduct, singleAxisProduct } from "./catalog-builders.js";
import type { DemoShopDefinition } from "./types.js";

/** Tech shop — phones, laptops, accessories. Handle has no dashes. */
export const techShop: DemoShopDefinition = {
  ids: {
    tenant: "d1000000-0000-4000-8000-000000000001",
    domain: "d1000000-0000-4000-8000-000000000002",
    user: "d1000000-0000-4000-8000-000000000003",
    account: "d1000000-0000-4000-8000-000000000003:credential",
    membership: "d1000000-0000-4000-8000-000000000004",
    onboarding: "d1000000-0000-4000-8000-000000000005",
    storefrontRevision: "d1000000-0000-4000-8000-000000000006",
    storefrontConfig: "d1000000-0000-4000-8000-000000000007",
  },
  templateKey: "nexahub@1",
  tenant: {
    handle: "addistech",
    name: "Addis Tech Hub",
  },
  user: {
    email: "yonatan@addistech.ecs.et",
    name: "Yonatan Bekele",
    phone: "+251911100001",
  },
  paymentOnboarding: {
    status: "not_configured",
    notes: "Demo shop — Chapa not connected (COD only).",
  },
  categories: [
    { name: "Phones", handle: "demo-tech-phones" },
    { name: "Android", handle: "demo-tech-phones-android", parentHandle: "demo-tech-phones" },
    { name: "Apple", handle: "demo-tech-phones-apple", parentHandle: "demo-tech-phones" },
    { name: "Laptops", handle: "demo-tech-laptops" },
    { name: "Windows", handle: "demo-tech-laptops-windows", parentHandle: "demo-tech-laptops" },
    { name: "Mac", handle: "demo-tech-laptops-mac", parentHandle: "demo-tech-laptops" },
    { name: "Audio", handle: "demo-tech-audio" },
    { name: "Accessories", handle: "demo-tech-accessories" },
  ],
  collections: [
    { title: "Best Sellers", handle: "demo-tech-best-sellers" },
    { title: "New Arrivals", handle: "demo-tech-new-arrivals" },
    { title: "Work From Home", handle: "demo-tech-wfh" },
  ],
  customers: [
    {
      firstName: "Abel",
      lastName: "Tesfaye",
      email: "abel.tesfaye.tech@example.com",
      phone: "+251911200101",
      area: "Bole",
      address: "Bole Medhanialem",
    },
    {
      firstName: "Sara",
      lastName: "Haile",
      email: "sara.haile.tech@example.com",
      phone: "+251911200102",
      area: "Kazanchis",
      address: "Kazanchis Business District",
    },
    {
      firstName: "Daniel",
      lastName: "Mekonnen",
      email: "daniel.mekonnen.tech@example.com",
      phone: "+251911200103",
      area: "CMC",
      address: "CMC Michael",
    },
    {
      firstName: "Hiwot",
      lastName: "Alemu",
      email: "hiwot.alemu.tech@example.com",
      phone: "+251911200104",
      area: "Piassa",
      address: "Arada Piassa",
    },
    {
      firstName: "Yared",
      lastName: "Girma",
      email: "yared.girma.tech@example.com",
      phone: "+251911200105",
      area: "Megenagna",
      address: "Megenagna Zefmesh",
    },
    {
      firstName: "Betty",
      lastName: "Assefa",
      email: "betty.assefa.tech@example.com",
      phone: "+251911200106",
      area: "Sarbet",
      address: "Sarbet Roundabout",
    },
    {
      firstName: "Kalkidan",
      lastName: "Wondimu",
      email: "kalkidan.wondimu.tech@example.com",
      phone: "+251911200107",
      area: "Ayat",
      address: "Ayat Square",
    },
    {
      firstName: "Mikiyas",
      lastName: "Tadesse",
      email: "mikiyas.tadesse.tech@example.com",
      phone: "+251911200108",
      area: "Mexico",
      address: "Mexico Square",
    },
    {
      firstName: "Eyerusalem",
      lastName: "Kassa",
      email: "eyerusalem.kassa.tech@example.com",
      phone: "+251911200109",
      area: "Gerji",
      address: "Gerji Mebrat Hail",
    },
  ],
  products: [
    {
      ...singleAxisProduct(
        "A35 5G Smartphone",
        "demo-tech-galaxy-a35",
        "phones",
        28900,
        "Storage",
        ["128GB", "256GB"],
        [18, 4],
      ),
      categoryHandle: "demo-tech-phones-android",
      collectionHandle: "demo-tech-best-sellers",
    },
    {
      ...singleAxisProduct(
        'Refurbished 6.1" Smartphone',
        "demo-tech-iphone-13",
        "phones",
        42500,
        "Storage",
        ["128GB", "256GB"],
        [6, 0],
      ),
      categoryHandle: "demo-tech-phones-apple",
      collectionHandle: "demo-tech-best-sellers",
    },
    {
      ...singleAxisProduct(
        "Note 13 Android Phone",
        "demo-tech-redmi-note-13",
        "phones",
        18900,
        "Config",
        ["8/256", "12/512"],
        [30, 12],
      ),
      categoryHandle: "demo-tech-phones-android",
      collectionHandle: "demo-tech-new-arrivals",
    },
    {
      ...singleAxisProduct(
        'E14 14" Business Laptop',
        "demo-tech-thinkpad-e14",
        "laptops",
        68900,
        "Config",
        ["i5 16GB", "i7 32GB"],
        [8, 2],
      ),
      categoryHandle: "demo-tech-laptops-windows",
      collectionHandle: "demo-tech-wfh",
    },
    {
      ...singleAxisProduct(
        'M1 13" Ultralight Laptop',
        "demo-tech-mba-m1",
        "laptops",
        79500,
        "Config",
        ["8/256", "16/512"],
        [5, 1],
      ),
      categoryHandle: "demo-tech-laptops-mac",
      collectionHandle: "demo-tech-wfh",
    },
    // Multi-axis: color × finish (exercises product picker axes).
    {
      ...matrixProduct(
        "Wireless Earbuds Pro",
        "demo-tech-earbuds-pro",
        "audio",
        4200,
        [
          { title: "Color", values: ["Black", "White"] },
          { title: "Case", values: ["Matte", "Gloss"] },
        ],
        [25, 10, 3, 0],
      ),
      categoryHandle: "demo-tech-audio",
      collectionHandle: "demo-tech-best-sellers",
    },
    {
      ...singleAxisProduct(
        "Over-Ear Studio Headphones",
        "demo-tech-studio-headphones",
        "audio",
        6800,
        "Color",
        ["Matte Black", "Navy"],
        [14, 7],
      ),
      categoryHandle: "demo-tech-audio",
      collectionHandle: "demo-tech-new-arrivals",
    },
    {
      ...singleAxisProduct(
        "65W GaN Charger",
        "demo-tech-gan-charger",
        "accessories",
        1800,
        "Ports",
        ["USB-C", "Multi-port"],
        [50, 20],
      ),
      categoryHandle: "demo-tech-accessories",
      collectionHandle: "demo-tech-new-arrivals",
    },
    {
      ...singleAxisProduct(
        "USB-C Hub 7-in-1",
        "demo-tech-usb-c-hub",
        "accessories",
        2400,
        "Finish",
        ["Space Grey", "Silver"],
        [22, 9],
      ),
      categoryHandle: "demo-tech-accessories",
      collectionHandle: "demo-tech-wfh",
    },
    {
      ...singleAxisProduct(
        'Laptop Sleeve 14"',
        "demo-tech-laptop-sleeve",
        "accessories",
        950,
        "Color",
        ["Graphite", "Sand"],
        [40, 15],
      ),
      categoryHandle: "demo-tech-accessories",
      collectionHandle: "demo-tech-wfh",
    },
    {
      ...singleAxisProduct(
        "Bluetooth Speaker Mini",
        "demo-tech-bt-speaker",
        "audio",
        2100,
        "Color",
        ["Charcoal", "Sage"],
        [16, 4],
      ),
      categoryHandle: "demo-tech-audio",
      collectionHandle: "demo-tech-best-sellers",
    },
    {
      ...singleAxisProduct(
        "Power Bank 20000mAh",
        "demo-tech-powerbank-20k",
        "accessories",
        2600,
        "Model",
        ["Standard", "PD Fast"],
        [28, 3],
      ),
      categoryHandle: "demo-tech-accessories",
      collectionHandle: "demo-tech-new-arrivals",
    },
  ],
};

/** Fashion shop — apparel and accessories (handle kept for shared test links). */
