export type {
  MerchantBatchDeleteActionResult,
  MerchantDeleteActionResult,
  MerchantProductCategoriesResult,
  MerchantProductCategoryMutationResult,
  MerchantProductCollectionMutationResult,
  MerchantProductCollectionsResult,
  MerchantProductMutationResult,
  MerchantProductResult,
  MerchantProductStockResult,
  MerchantProductsResult,
  MerchantProductWriteInput,
} from "@/lib/platform-api/products";
export {
  createMerchantProduct,
  createMerchantProductCategory,
  createMerchantProductCollection,
  deleteMerchantProduct,
  deleteMerchantProductCategoriesBatch,
  deleteMerchantProductCategory,
  deleteMerchantProductCollection,
  deleteMerchantProductCollectionsBatch,
  deleteMerchantProductsBatch,
  getMerchantProduct,
  getMerchantProductCategories,
  getMerchantProductCollections,
  getMerchantProductStock,
  getMerchantProducts,
  getMerchantProductVariantStock,
  reorderMerchantProductCategories,
  updateMerchantProduct,
  updateMerchantProductCategory,
  updateMerchantProductCollection,
  updateMerchantProductStock,
  updateMerchantProductVariantStock,
} from "@/lib/platform-api/products";
